### ISSUE TITLE
Add support for Query endpoint of Bulk API

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-salesforce-source#6]
Use existing jsforce library--
https://jsforce.github.io/document/#bulk-query

**Comment by dansweet1** [comment]
Discussed with Mike updating this source and what that would entail as to avoid as much technical debt as possible when I start this tomorrow. Feel good about adding the query endpoint of bulk api.

**Comment by dansweet1** [comment]
Reading up on jsforce library, then crushing this. Need to update tests, remove any outdated practices, update package.json.

**Comment by benjamingregory** [comment]
@JoshuaThompson Close if no longer relevant with your changes.

**Comment by ryw** [comment]
no more work on aries
